language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dgeni' ]; then cd .. && eval "mv $currentfolder generator-dgeni" && cd generator-dgeni; fi
